name: Update eos-tzdata

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"
  push:
    paths:
      # if we change any of the non-generated items in tzdata, recheck
      - "eos-tzdata/**"
      - "!eos-tzdata/VERSION"
      - "!eos-tzdata/src/data.rs"
      - "!eos-tzdata/src/README//md"

concurrency:
  # since this runs on an interval this should be fine
  # but we want concurrency failures since we're doing commits
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

jobs:
  update-tz-data:
    name: Update eos-tzdata using Python 3.x
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python deps
        run: |
          python -m pip install -U requests

      - name: Revert last commit if it was GitHub Actions
        run: |
          if [[ "$(git show -s --format='%ae' HEAD)" == *"github-actions"* ]]; then
            git reset --hard HEAD^;
          fi

      - name: Run update script
        run: |
          cd eos-tzdata/
          python update.py

      - name: Check if tzdata has been updated
        run: |
          ! git diff --exit-code eos-tzdata/VERSION

      - name: Commit and push changes
        # the --exit-code above will return 1 (fail) if the file given has changed
        # we negate that with `!`
        # success() ensures the previous job succeeds
        if: ${{ success() }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Autogenerated commit for eos-tzdata update $(date +%Y-%m-%d_%H-%M)"
          git push --force
